name: Build, Test and Publish Allure Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      BROWSER: chrome  # Change to 'firefox' if you want to run tests on Firefox

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Browser setup
      - name: Setup browser dependencies
        if: env.BROWSER == 'chrome'
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Setup ChromeDriver
        if: env.BROWSER == 'chrome'
        uses: nanasess/setup-chromedriver@v1
        with:
          version: latest

      - name: Setup Firefox
        if: env.BROWSER == 'firefox'
        run: sudo apt-get install -y firefox

      - name: Setup GeckoDriver
        if: env.BROWSER == 'firefox'
        uses: matthew-brett/geckodriver-action@v1
        with:
          version: latest

      - name: Run tests and generate Allure results
        run: mvn clean test -Dbrowser=${{ env.BROWSER }}

      - name: Generate Allure report
        run: mvn allure:report

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Download Allure report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
